name: Build and deploy on production server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./dist
          retention-days: 1
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./dist
      - name: Deploy
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -rav --delete
          path: ./dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
